# Generated by Django 3.0.6 on 2020-05-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_PIB', models.CharField(max_length=64, verbose_name='Your name')),
                ('resume_email', models.EmailField(max_length=20, verbose_name='Email')),
                ('resume_adress', models.CharField(max_length=150, verbose_name='Home adress')),
                ('resume_phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('resume_github', models.URLField(blank=True, max_length=30, verbose_name='Github link')),
                ('resume_position', models.CharField(max_length=30, verbose_name='Position')),
                ('resume_experience', models.CharField(max_length=30, verbose_name='Experience')),
                ('resume_education', models.CharField(max_length=30, verbose_name='Education')),
                ('resume_lng_c_plus', models.CharField(max_length=20, verbose_name='C/C++')),
                ('resume_lng_c_sharp', models.CharField(max_length=20, verbose_name='C#')),
                ('resume_lng_pascal', models.CharField(max_length=20, verbose_name='Pascal')),
                ('resume_lng_java', models.CharField(max_length=20, verbose_name='Java')),
                ('resume_lng_html_css', models.CharField(max_length=20, verbose_name='Html/Css')),
                ('resume_lng_JS', models.CharField(max_length=20, verbose_name='JavaScript')),
                ('resume_lng_Bootstrap', models.CharField(max_length=20, verbose_name='Bootstrap')),
                ('resume_lng_php', models.CharField(max_length=20, verbose_name='PHP')),
                ('resume_lng_python', models.CharField(max_length=20, verbose_name='Python')),
                ('resume_lng_django', models.CharField(max_length=20, verbose_name='Django')),
                ('resume_lng_NET', models.CharField(max_length=20, verbose_name='.Net')),
                ('resume_lng_nodejs', models.CharField(max_length=20, verbose_name='Node.js')),
                ('resume_cms_wordpress', models.CharField(max_length=20, verbose_name='Wordpress')),
                ('resume_cms_joomla', models.CharField(max_length=20, verbose_name='Joomla')),
                ('resume_cms_drupal', models.CharField(max_length=20, verbose_name='Drupal')),
                ('resume_os_windows', models.CharField(max_length=20, verbose_name='Windows')),
                ('resume_os_linux', models.CharField(max_length=20, verbose_name='Linux')),
                ('resume_os_macos', models.CharField(max_length=20, verbose_name='MacOS')),
                ('resume_english', models.CharField(max_length=20, verbose_name='English')),
                ('resume_rus', models.CharField(max_length=20, verbose_name='Russian')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Ім`я автора коментарію')),
                ('comment_text', models.TextField(verbose_name='Текст коментарію')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
            options={
                'verbose_name': 'Коментарій',
                'verbose_name_plural': 'Коментарі',
            },
        ),
    ]
