# Generated by Django 3.0.6 on 2020-05-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_rus',
        ),
    ]
