# Generated by Django 3.0.6 on 2020-05-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200517_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='resume_date',
            field=models.DateTimeField(verbose_name='Date public resume'),
        ),
    ]
