# Generated by Django 3.0.6 on 2020-05-10 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_PIB', models.CharField(max_length=64, verbose_name='ПІБ власника резюме')),
                ('resume_position', models.CharField(max_length=30, verbose_name='Бажана посада')),
                ('resume_contact_adress', models.CharField(max_length=150, verbose_name='Адреса проживання')),
                ('resume_contact_phone', models.CharField(max_length=20, verbose_name='ПІБ власника резюме')),
                ('resume_date', models.DateTimeField(verbose_name='Дата подання резюме')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Ім`я автора коментарію')),
                ('comment_text', models.TextField(verbose_name='Текст коментарію')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume')),
            ],
        ),
    ]
