# Generated by Django 3.0.6 on 2020-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарій', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Резюме', 'verbose_name_plural': 'Резюме'},
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_contact_adress',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_contact_phone',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_adress',
            field=models.CharField(default='Home adress', max_length=150, verbose_name='Home adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_email',
            field=models.EmailField(default='example@gmail.com', max_length=20, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_experience',
            field=models.CharField(default='default', max_length=30, verbose_name='Position'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_github',
            field=models.URLField(default='default', max_length=30, verbose_name='Github link'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_phone',
            field=models.CharField(default='default', max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_PIB',
            field=models.CharField(max_length=64, verbose_name='Your name'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='resume_position',
            field=models.CharField(max_length=30, verbose_name='Position'),
        ),
    ]
