# Generated by Django 3.0.6 on 2020-05-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200517_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='resume_birthday',
            new_name='resume_birthdayy',
        ),
    ]
