# Generated by Django 3.0.6 on 2020-05-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20200517_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_birthdayy',
        ),
    ]
