# Generated by Django 3.0.6 on 2020-05-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_remove_resume_resume_birthdayy'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_birthday',
            field=models.CharField(blank=True, max_length=30, verbose_name='Birthday'),
        ),
    ]
