# Generated by Django 3.0.6 on 2020-05-17 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_resume_resume_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_birthday',
        ),
    ]
