# Generated by Django 3.0.6 on 2020-05-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_remove_resume_resume_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_cms_drupal',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_cms_joomla',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_cms_wordpress',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_english',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_github',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_Bootstrap',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_JS',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_NET',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_c_plus',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_c_sharp',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_django',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_html_css',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_java',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_nodejs',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_pascal',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_php',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_lng_python',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_os_linux',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_os_macos',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_os_windows',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_position',
        ),
    ]
