# Generated by Django 3.0.6 on 2020-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_remove_resume_resume_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подання резюме'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_experience',
            field=models.CharField(default='def', max_length=30, verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_github',
            field=models.URLField(blank=True, max_length=30, verbose_name='Github link'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_position',
            field=models.CharField(default='def', max_length=30, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
