# Generated by Django 3.0.6 on 2020-05-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20200517_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_adress',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_github',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_position',
        ),
    ]
