# Generated by Django 3.0.6 on 2020-05-17 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20200517_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_adress',
            field=models.CharField(default='def', max_length=150, verbose_name='Home adress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_cms_drupal',
            field=models.CharField(default='def', max_length=20, verbose_name='Drupal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_cms_joomla',
            field=models.CharField(default='def', max_length=20, verbose_name='Joomla'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_cms_wordpress',
            field=models.CharField(default='def', max_length=20, verbose_name='Wordpress'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date public resume'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_education',
            field=models.CharField(default='def', max_length=30, verbose_name='Education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_english',
            field=models.CharField(default='def', max_length=20, verbose_name='English'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_experience',
            field=models.CharField(default='def', max_length=30, verbose_name='Experience'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_github',
            field=models.URLField(blank=True, max_length=30, verbose_name='Github link'),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_Bootstrap',
            field=models.CharField(default='def', max_length=20, verbose_name='Bootstrap'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_JS',
            field=models.CharField(default='def', max_length=20, verbose_name='JavaScript'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_NET',
            field=models.CharField(default='def', max_length=20, verbose_name='.Net'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_c_plus',
            field=models.CharField(default='def', max_length=20, verbose_name='C/C++'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_c_sharp',
            field=models.CharField(default='def', max_length=20, verbose_name='C#'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_django',
            field=models.CharField(default='def', max_length=20, verbose_name='Django'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_html_css',
            field=models.CharField(default='def', max_length=20, verbose_name='Html/Css'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_java',
            field=models.CharField(default='def', max_length=20, verbose_name='Java'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_nodejs',
            field=models.CharField(default='def', max_length=20, verbose_name='Node.js'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_pascal',
            field=models.CharField(default='def', max_length=20, verbose_name='Pascal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_php',
            field=models.CharField(default='def', max_length=20, verbose_name='PHP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_lng_python',
            field=models.CharField(default='def', max_length=20, verbose_name='Python'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_os_linux',
            field=models.CharField(default='def', max_length=20, verbose_name='Linux'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_os_macos',
            field=models.CharField(default='def', max_length=20, verbose_name='MacOS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_os_windows',
            field=models.CharField(default='def', max_length=20, verbose_name='Windows'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_phone',
            field=models.CharField(default='def', max_length=20, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_position',
            field=models.CharField(default='def', max_length=30, verbose_name='Position'),
            preserve_default=False,
        ),
    ]
