# Generated by Django 3.0.6 on 2020-05-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20200517_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='resume_birthday',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='resume_date',
        ),
    ]
