# Generated by Django 3.0.6 on 2020-05-17 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_remove_resume_resume_rus'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Birthday'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date public resume'),
            preserve_default=False,
        ),
    ]
