# Generated by Django 3.0.6 on 2020-05-18 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200518_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.Resume'),
        ),
    ]
