# Generated by Django 3.0.6 on 2020-06-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_auto_20200605_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='system_position',
            field=models.CharField(blank=True, max_length=30, verbose_name='System position'),
        ),
    ]
